In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4, 
                   'k2': [1, 1, 2, 3, 3, 4, 4]})

In [3]:
DF

NameError: name 'DF' is not defined

In [4]:
df

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [6]:
df.duplicated()
#중복된 행을 True로 나타나게 해준다

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [8]:
df.drop_duplicates()
#중복된 행을 삭제하고 데이터 나타나게 해줌

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [9]:
df["v1"] = np.arange(7)

In [10]:
df

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [13]:
df.drop_duplicates(["k1"])
#k1의 값을 보고 중복을 제거하겠다

k1  k2  v1
0  one   1   0
3  two   3   3

In [16]:
df.drop_duplicates(["k1","k2"], keep="last")
#k1, k2의 값을 기준으로 정렬하고 중복 발생했을때 뒤쪽 데이터를 남긴다

k1  k2  v1
1  one   1   1
2  one   2   2
4  two   3   4
6  two   4   6

In [17]:
df2 = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 
                             'corned beef', 'Bacon', 'pastrami', 'honey ham',
                             'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [19]:
df2

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [20]:
meat_to_animal = { 
    'bacon': 'pig', 
    'pulled pork': 'pig', 
    'pastrami': 'cow', 
    'corned beef': 'cow', 
    'honey ham': 'pig', 
    'nova lox': 'salmon'
}

In [21]:
df2["animal"] = df2["food"].apply(lambda x: meat_to_animal[x.lower()])
#lower는 소문자로 치환

In [22]:
df2

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [23]:
s = pd.Series([1., -999., 2., -999., -1000., 3.])

In [24]:
s

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [26]:
s2 = s.replace(-999, np.nan)
#이상치를 쉽게 변경 가능하다

In [27]:
s2

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [28]:
s2.replace(np.nan,0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [29]:
s2.fillna(0)

0       1.0
1       0.0
2       2.0
3       0.0
4   -1000.0
5       3.0
dtype: float64

In [30]:
# 카테고리(categories)
df3 = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})

In [31]:
df3

id raw_grade
0   1         a
1   2         b
2   3         b
3   4         a
4   5         a
5   6         e

In [32]:
df3["grade"] = df3["raw_grade"].astype("category")

In [33]:
df3

id raw_grade grade
0   1         a     a
1   2         b     b
2   3         b     b
3   4         a     a
4   5         a     a
5   6         e     e

In [34]:
df3["grade"]

0    a
1    b
2    b
3    a
4    a
5    e
Name: grade, dtype: category
Categories (3, object): [a, b, e]

In [35]:
df3["grade"].cat.categories

Index(['a', 'b', 'e'], dtype='object')

In [36]:
df3["grade"].cat.categories = ["very good", "good", "very bad"]
#카테고리의 데이터 값을 변경시킨다

In [37]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [38]:
df3["grade"] = df3["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])
#카테고리를 추가한다

In [40]:
df3["grade"]
#3개에서 5개로 변경됨

0    very good
1         good
2         good
3    very good
4    very good
5     very bad
Name: grade, dtype: category
Categories (5, object): [very bad, bad, medium, good, very good]

In [41]:
df3

id raw_grade      grade
0   1         a  very good
1   2         b       good
2   3         b       good
3   4         a  very good
4   5         a  very good
5   6         e   very bad

In [44]:
df3.sort_values(by="grade")
#정렬 가능

id raw_grade      grade
5   6         e   very bad
1   2         b       good
2   3         b       good
0   1         a  very good
3   4         a  very good
4   5         a  very good

In [45]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]

In [50]:
cats = pd.cut(ages,bins)
#데이터 값을 구간별로 나눌 수 있다

In [47]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [48]:
cats.categories

Index(['(18, 25]', '(25, 35]', '(35, 60]', '(60, 100]'], dtype='object')

In [49]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [51]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [52]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [54]:
pd.cut(ages,bins,labels=group_names)
#카테로기 이름을 지정해서 할 수 있다

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [55]:
data = np.random.rand(20)

In [56]:
data

array([ 0.83289579,  0.63999684,  0.3107839 ,  0.43322207,  0.57960055,
        0.46640275,  0.80052479,  0.93057924,  0.52164768,  0.31793058,
        0.70824905,  0.03977845,  0.13542949,  0.38841834,  0.87023553,
        0.53462031,  0.77936112,  0.17793374,  0.55356176,  0.61089174])

In [57]:
pd.cut(data,4,precision=2)
#컷 안에 데이터를 넣고 4개로 구분시킨다 precision은 구간 기준값 소수점 2자리까지 구분한다

[(0.71, 0.93], (0.49, 0.71], (0.26, 0.49], (0.26, 0.49], (0.49, 0.71], ..., (0.49, 0.71], (0.71, 0.93], (0.039, 0.26], (0.49, 0.71], (0.49, 0.71]]
Length: 20
Categories (4, object): [(0.039, 0.26] < (0.26, 0.49] < (0.49, 0.71] < (0.71, 0.93]]

In [58]:
data2 = np.random.randn(1000)

In [59]:
data2[:5]

array([  1.04093342e-03,  -1.23827909e+00,  -1.69454367e+00,
        -7.97014723e-01,  -1.33968225e+00])

In [62]:
cats = pd.qcut(data2, 4)
#자동으로 4개로 구분해준다

In [61]:
cats

[(-0.013, 0.705], [-3.178, -0.703], [-3.178, -0.703], [-3.178, -0.703], [-3.178, -0.703], ..., (0.705, 3.784], (0.705, 3.784], (-0.013, 0.705], (0.705, 3.784], [-3.178, -0.703]]
Length: 1000
Categories (4, object): [[-3.178, -0.703] < (-0.703, -0.013] < (-0.013, 0.705] < (0.705, 3.784]]