In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr[:]

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [10]:
arr2d(2,:)

SyntaxError: invalid syntax (<ipython-input-10-daab5949c211>, line 1)

In [11]:
arr2d[2,:]

array([ 9, 10, 11, 12])

In [12]:
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr2d[:,3]

array([ 4,  8, 12, 16])

In [14]:
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [15]:
arr2d[3,2]

15

In [16]:
arr2d[:2,1:3]

array([[2, 3],
       [6, 7]])

In [17]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
arr2d[:2,1:3]=0

In [19]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
 names = np.array(["Charles", "Kilho", "Hayoung", "Charles", "Hayoung", "Kilho", "Kilho"])
data=np.random.randn(7,4)

In [21]:
names

array(['Charles', 'Kilho', 'Hayoung', 'Charles', 'Hayoung', 'Kilho',
       'Kilho'], 
      dtype='<U7')

In [22]:
data

array([[  1.44429601e+00,   7.81400248e-01,  -8.29255149e-01,
          1.59208385e+00],
       [  9.55276620e-01,   7.46777936e-02,   1.44810276e+00,
         -1.18623230e+00],
       [ -1.28993229e+00,  -8.77997695e-04,   7.84838535e-01,
         -1.74738072e+00],
       [  3.03861896e-01,  -3.89994901e-01,   2.75888490e-01,
         -1.88741242e-01],
       [  4.96212905e-01,   2.46488196e-01,  -7.29628709e-01,
         -2.41424652e+00],
       [  1.11325062e+00,   5.67001201e-01,   1.73610478e+00,
         -5.26423567e-01],
       [  1.06537301e+00,   1.82436665e-02,  -1.09695272e+00,
         -3.65855557e-01]])

In [23]:
names == "Charles"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [25]:
data[names == "Charles",:]

array([[ 1.44429601,  0.78140025, -0.82925515,  1.59208385],
       [ 0.3038619 , -0.3899949 ,  0.27588849, -0.18874124]])

In [28]:
data[(names=="Charles")|(names=="Kilho"),:]

array([[ 1.44429601,  0.78140025, -0.82925515,  1.59208385],
       [ 0.95527662,  0.07467779,  1.44810276, -1.1862323 ],
       [ 0.3038619 , -0.3899949 ,  0.27588849, -0.18874124],
       [ 1.11325062,  0.5670012 ,  1.73610478, -0.52642357],
       [ 1.06537301,  0.01824367, -1.09695272, -0.36585556]])

In [29]:
DATA[:,3]

NameError: name 'DATA' is not defined

In [30]:
data[:,3]

array([ 1.59208385, -1.1862323 , -1.74738072, -0.18874124, -2.41424652,
       -0.52642357, -0.36585556])

In [31]:
data[:,3] <0

array([False,  True,  True,  True,  True,  True,  True], dtype=bool)