In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
np.log10(arr)

array([ 0.        ,  0.30103   ,  0.47712125,  0.60205999,  0.69897   ,
        0.77815125,  0.84509804,  0.90308999,  0.95424251])

In [6]:
x = np.random.randn(8)
y = np.random.randn(8)

In [7]:
x

array([ 0.132041  , -0.29577764, -0.99570068, -0.00908824,  0.93258126,
        0.22448131,  0.31013793, -0.51045452])

In [8]:
y

array([-0.03861822, -0.37420313, -0.93009082,  0.3516138 , -0.10861206,
        1.29588882,  0.79640676, -1.00450517])

In [9]:
np.maximum(x,y)

array([ 0.132041  , -0.29577764, -0.93009082,  0.3516138 ,  0.93258126,
        1.29588882,  0.79640676, -0.51045452])

In [10]:
arr = np.random.randn(5,4)

In [11]:
arr

array([[ 0.50023391, -0.18513402,  0.50596302,  0.25929403],
       [-0.67139695, -0.31324559, -0.65141888, -1.55732006],
       [-1.31863846,  0.68103647,  1.26118202,  0.5556716 ],
       [-0.4801859 ,  0.16261416, -0.98858261, -0.360196  ],
       [-0.72422032, -0.07615418, -0.36867736,  2.33628689]])

In [12]:
arr.sum()

-1.432888217068724

In [13]:
arr.mean()

-0.071644410853436202

In [14]:
arr.sum(axis=0)

array([-2.69420771,  0.26911684, -0.2415338 ,  1.23373645])

In [15]:
arr.sum(axis=1)

array([ 1.08035695, -3.19338148,  1.17925163, -1.66635035,  1.16723504])

In [16]:
arr >0

array([[ True, False,  True,  True],
       [False, False, False, False],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [False, False, False,  True]], dtype=bool)

In [17]:
(arr>0).sum()

8

In [18]:
arr = np.random.randn(8)

In [19]:
arr

array([ 0.41939431, -0.94434232,  0.24122212, -0.62889616, -0.85779037,
       -0.40526346, -0.29406013,  1.44139924])

In [20]:
np.sort(arr)

array([-0.94434232, -0.85779037, -0.62889616, -0.40526346, -0.29406013,
        0.24122212,  0.41939431,  1.44139924])

In [21]:
np.sort(arr)[::-1]

array([ 1.44139924,  0.41939431,  0.24122212, -0.29406013, -0.40526346,
       -0.62889616, -0.85779037, -0.94434232])

In [22]:
arr = np.random.randn(5,3)

In [23]:
arr

array([[ 1.23333782,  1.33765425, -1.30449174],
       [ 0.03531229, -2.34697946, -0.66335531],
       [ 0.40195706, -0.3729995 ,  0.34041421],
       [-1.28641361, -0.71043293, -1.70662176],
       [ 0.78183637, -0.90279646,  1.24119694]])

In [24]:
np.sort[arr,axis=0]

SyntaxError: invalid syntax (<ipython-input-24-ad13d43d98c2>, line 1)

In [25]:
np.sort(arr,axis=0)

array([[-1.28641361, -2.34697946, -1.70662176],
       [ 0.03531229, -0.90279646, -1.30449174],
       [ 0.40195706, -0.71043293, -0.66335531],
       [ 0.78183637, -0.3729995 ,  0.34041421],
       [ 1.23333782,  1.33765425,  1.24119694]])

In [26]:
np.sort(arr,axis=1)

array([[-1.30449174,  1.23333782,  1.33765425],
       [-2.34697946, -0.66335531,  0.03531229],
       [-0.3729995 ,  0.34041421,  0.40195706],
       [-1.70662176, -1.28641361, -0.71043293],
       [-0.90279646,  0.78183637,  1.24119694]])

In [27]:
large_arr = np.random.randn(150)

In [28]:
arr

array([[ 1.23333782,  1.33765425, -1.30449174],
       [ 0.03531229, -2.34697946, -0.66335531],
       [ 0.40195706, -0.3729995 ,  0.34041421],
       [-1.28641361, -0.71043293, -1.70662176],
       [ 0.78183637, -0.90279646,  1.24119694]])

In [29]:
large_arr

array([ 0.97128176,  0.85245619, -0.6793697 ,  0.52577356, -0.29925786,
       -1.44959673,  0.2550769 , -1.34068903,  2.36179788,  0.24938879,
       -0.54034379, -0.59494483,  0.56937303, -0.44721982, -0.45029003,
       -0.19886635,  0.15982109, -0.12476489, -0.55726211,  0.21518523,
       -0.65421398, -0.52471682, -0.01375516, -2.39077361, -1.4692868 ,
        0.70533281, -0.01796958, -0.55204443, -0.50378366,  2.32730007,
        0.7655319 ,  0.178629  ,  0.91048516, -1.32648244,  0.77343268,
       -0.32688792,  0.77238609,  0.20172294, -0.74566714,  0.27936657,
       -0.01420675,  0.48035293,  0.80196968,  0.88641737,  0.24296693,
       -0.62270411,  0.05728735, -0.37013753,  0.58557908, -1.18760998,
       -1.37823008, -1.26211314,  0.18851626,  0.30222289, -1.82086856,
       -1.52297454, -1.46775465,  1.23966161,  0.03651264, -1.1217569 ,
       -0.59229405,  1.00139911,  0.0679566 ,  0.14047364, -0.81435343,
       -1.40976464, -0.23989198,  0.24940239, -1.39487824,  1.51

In [30]:
np.sort(large_arr)

array([-2.65613805, -2.39077361, -2.19976063, -1.82086856, -1.78210355,
       -1.71717587, -1.64903997, -1.55241863, -1.54547105, -1.52297454,
       -1.4692868 , -1.46775465, -1.44959673, -1.43969963, -1.43733036,
       -1.40976464, -1.39487824, -1.37823008, -1.34068903, -1.32648244,
       -1.26211314, -1.23620367, -1.20517969, -1.18760998, -1.16444187,
       -1.13141044, -1.1217569 , -1.08638292, -0.88981893, -0.81435343,
       -0.79232128, -0.76263119, -0.74566714, -0.73201279, -0.70881237,
       -0.6793697 , -0.65817359, -0.65421398, -0.65406625, -0.62270411,
       -0.59494483, -0.59229405, -0.56240093, -0.55726211, -0.55204443,
       -0.54034379, -0.52471682, -0.52152204, -0.50378366, -0.49696986,
       -0.45029003, -0.44721982, -0.3768934 , -0.37013753, -0.341162  ,
       -0.33509842, -0.32688792, -0.29925786, -0.2771882 , -0.26686147,
       -0.24888497, -0.24617959, -0.24517974, -0.23989198, -0.20044991,
       -0.19886635, -0.19848111, -0.14347694, -0.12476489, -0.12

In [31]:
np.sort(large_arr)[::-1]

array([ 2.36179788,  2.32730007,  2.30078881,  2.15276048,  2.02641579,
        1.515416  ,  1.4263895 ,  1.34278558,  1.27718279,  1.24557828,
        1.23966161,  1.22031015,  1.22021864,  1.16640199,  1.13132172,
        1.11969659,  1.10050297,  1.00139911,  0.97368848,  0.97128176,
        0.91318911,  0.91048516,  0.9046343 ,  0.90061746,  0.8944785 ,
        0.88641737,  0.85245619,  0.84464825,  0.83328381,  0.81058287,
        0.80196968,  0.79678839,  0.77343268,  0.77238609,  0.7655319 ,
        0.76113916,  0.73625903,  0.7233352 ,  0.70943097,  0.70533281,
        0.69184023,  0.58557908,  0.56937303,  0.55414144,  0.53937929,
        0.53092872,  0.52577356,  0.51805772,  0.50955323,  0.48035293,
        0.45697912,  0.40705035,  0.3319997 ,  0.30290157,  0.30222289,
        0.2857949 ,  0.27936657,  0.2550769 ,  0.24940239,  0.24938879,
        0.24365405,  0.24296693,  0.21518523,  0.20172294,  0.18851626,
        0.178629  ,  0.15982109,  0.15445966,  0.14047364,  0.10

In [32]:
np.sort(large_arr)[::-1][int(0.05 * len(large_arr))]

1.342785583794359