In [1]:
import numpy as np

In [2]:
data = np.loadtxt("data/movielens-1m/ratings.dat", delimiter="::", dtype=np.int64)

In [3]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [4]:
data.shape

(1000209, 4)

In [5]:
#전체 평균 펑점 계산하기
mean_rating_total = data[:,2].mean()

In [6]:
mean_rating_total

3.5815644530293169

In [7]:
#각 사용자 별 평균 평점 계산하기
user_ids=np.unique(data[:,0])

In [8]:
user_ids[:5]

array([1, 2, 3, 4, 5], dtype=int64)

In [9]:
user_ids.shape

(6040,)

In [10]:
mean_rating_by_user_list=[]
for user_id in user_ids:
    data_for_user = data[data[:,0]==user_id,:]
    mean_rating_for_user = data_for_user[:,2].mean()
    mean_rating_by_user_list.append([user_id,mean_rating_for_user])

In [11]:
mean_rating_by_user_listby_list[:5]

NameError: name 'mean_rating_by_user_listby_list' is not defined

  mean_rating_by_user_list

In [12]:
mean_rating_by_user_list

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.8848920863309351],
 [9, 3.7358490566037736],
 [10, 4.1147132169576057],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.3888888888888888],
 [14, 3.3199999999999998],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.0758293838862558],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.9090909090909092],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.9485294117647061],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.1714285714285717],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.4883720930232558],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.4987212276214832],
 [34, 3.8658536585365852],
 [35, 3.5404040404040402],
 [36, 4.199430199430199],
 [37, 3.6981132075471699],
 [38, 3.5800000000000001],
 [39, 3.56451612

In [13]:
mean_rating_by_user_list[:5]

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466]]

In [14]:
mean_rating_by_user_array = np.array(mean_rating_by_user_list,dtype=np.float32)

In [15]:
mean_rating_by_user_array[:5]

array([[ 1.        ,  4.18867922],
       [ 2.        ,  3.7131784 ],
       [ 3.        ,  3.90196085],
       [ 4.        ,  4.19047642],
       [ 5.        ,  3.14646459]], dtype=float32)

In [16]:
mean_rating_by_user_array.shape

(6040, 2)

In [ ]:
np.savetxt("mean_rating_by_user.csv",mean_rating_by_user_array,fmt='%.3f', delimiter=',')

In [ ]:
data_for_user

In [ ]:
data_for_user[:5]

In [ ]:
mean_rating_for_user[:]

In [ ]:
mean_rating_for_user

In [ ]:
mean_rating_for_user[:]

In [ ]:
mean_rating_by_user_list[:5]

In [ ]:
%who

In [ ]:
data[user_id,:]

In [ ]:
user_id

In [ ]:
%who

In [18]:
data[user_id,:]

array([       44,      1952,         3, 978019279], dtype=int64)

In [ ]:
%who

In [17]:
%who

data	 data_for_user	 mean_rating_by_user_array	 mean_rating_by_user_list	 mean_rating_for_user	 mean_rating_total	 np	 user_id	 user_ids	 



In [19]:
user_id[:5]

IndexError: invalid index to scalar variable.

In [21]:
user_id.shape

()

In [23]:
data_for_user[:,2]

array([4, 4, 3, 4, 2, 5, 2, 1, 4, 3, 5, 2, 4, 4, 4, 4, 5, 5, 3, 5, 5, 3, 5,
       5, 1, 2, 1, 4, 4, 3, 1, 1, 3, 3, 1, 4, 5, 5, 2, 4, 4, 4, 4, 3, 1, 2,
       3, 3, 1, 3, 3, 2, 5, 4, 3, 5, 2, 5, 2, 2, 4, 4, 4, 3, 4, 5, 4, 4, 5,
       3, 4, 4, 4, 2, 3, 5, 4, 4, 4, 5, 4, 1, 4, 2, 4, 5, 5, 4, 5, 1, 4, 3,
       3, 5, 1, 2, 3, 4, 4, 5, 5, 5, 2, 5, 4, 5, 1, 5, 1, 3, 4, 5, 4, 3, 4,
       2, 4, 4, 5, 1, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4, 3, 2, 5, 3, 3, 2, 4,
       4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 4, 3, 4, 4, 5, 1, 1, 3, 4, 4, 5, 4, 1,
       3, 5, 4, 5, 2, 5, 5, 4, 4, 3, 5, 5, 2, 4, 5, 3, 5, 4, 2, 4, 4, 5, 3,
       3, 4, 2, 3, 4, 1, 4, 4, 2, 4, 5, 5, 4, 4, 5, 3, 4, 4, 3, 3, 4, 4, 3,
       4, 5, 4, 4, 4, 5, 4, 5, 5, 3, 2, 4, 4, 2, 3, 1, 3, 4, 4, 4, 5, 1, 5,
       4, 4, 4, 5, 4, 2, 5, 4, 4, 5, 5, 3, 3, 2, 5, 4, 4, 4, 4, 4, 4, 4, 4,
       5, 4, 5, 2, 3, 4, 4, 4, 3, 5, 4, 5, 3, 3, 4, 2, 3, 4, 5, 3, 4, 2, 4,
       5, 3, 3, 3, 4, 5, 2, 1, 5, 4, 5, 2, 4, 4, 3, 3, 4, 2, 4, 3, 2, 2, 1,
       3, 4,